---
# Configure Grafana

- name: Ensure Grafana datasources directory exists
  file:
    path: /etc/grafana/datasources
    state: directory
    mode: '0755'

- name: Copy Grafana datasource configuration
  copy:
    src: "{{ playbook_dir }}/../configs/grafana/datasources.yml"
    dest: /etc/grafana/datasources/datasources.yml
    mode: '0644'
