---
# Configure Node Exporter

- name: Install Node Exporter
  apt:
    name: prometheus-node-exporter
    state: present
    update_cache: yes

- name: Ensure Node Exporter is running
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Configure Node Exporter to listen on all interfaces
  lineinfile:
    path: /etc/default/prometheus-node-exporter
    regexp: '^ARGS='
    line: 'ARGS="--web.listen-address=:9100"'
    create: yes
  notify: restart node-exporter
